# Generated by Django 5.2.3 on 2025-07-03 17:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_panel", "0002_alter_company_vehicle_tempo_doors_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("Oil Change", "Oil Change"),
                            ("Tyre Replacement", "Tyre Replacement"),
                            ("Brake Service", "Brake Service"),
                            ("General Service", "General Service"),
                            ("Battery Check", "Battery Check"),
                            ("Engine Work", "Engine Work"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("service_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "odometer_reading",
                    models.PositiveIntegerField(help_text="KM at time of service"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("next_service_due_date", models.DateField(blank=True, null=True)),
                (
                    "next_service_due_km",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "service_center",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="maintenance_docs/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="admin_panel.driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="admin_panel.company_vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-service_date"],
            },
        ),
    ]
