# Generated by Django 5.2.3 on 2025-07-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver_panel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehiclemaintenance",
            name="id",
        ),
        migrations.AddField(
            model_name="vehiclemaintenance",
            name="service_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="vehiclemaintenance",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("Oil Change", "Oil Change"),
                    ("Tyre Replacement", "Tyre Replacement"),
                    ("Brake Service", "Brake Service"),
                    ("General Service", "General Service"),
                    ("Battery Check", "Battery Check"),
                    ("Engine Work", "Engine Work"),
                    ("Tire Rotation", "Tire Rotation"),
                    ("Transmission Service", "Transmission Service"),
                    ("Air Filter Replacement", "Air Filter Replacement"),
                    ("Coolant Flush", "Coolant Flush"),
                    ("Radiator Flush", "Radiator Flush"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
