# Generated by Django 5.2.3 on 2025-07-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_rename_profile_image_driver_driver_profile_image"),
        ("driver_panel", "0002_remove_vehiclemaintenance_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="leave_request",
            fields=[
                ("leave_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.driver",
                    ),
                ),
            ],
        ),
    ]
