# Generated by Django 5.2.3 on 2025-06-30 17:51

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="admin_Register",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("confirm_password", models.CharField(max_length=100)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.branch",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("driver_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="driver_images/"
                    ),
                ),
                (
                    "vehicle_link",
                    models.CharField(
                        choices=[
                            ("own", "Own Vehicle"),
                            ("company", "Company Vehicle"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "driving_licence",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vehicle_driver_type",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[("2", "2 wheeler"), ("4", "4 wheeler")],
                        max_length=10,
                    ),
                ),
                (
                    "company_email",
                    models.EmailField(blank=True, max_length=254, unique=True),
                ),
                ("password", models.CharField(blank=True, max_length=100)),
                ("joined_at", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Not Available", "Not Available"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.admin_register",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="company_vehicle",
            fields=[
                ("vehicle_id", models.AutoField(primary_key=True, serialize=False)),
                ("vehicle_name", models.CharField(max_length=100)),
                ("vehicle_model", models.CharField(max_length=100)),
                ("vehicle_number", models.CharField(max_length=20)),
                ("vehicle_color", models.CharField(max_length=50)),
                ("vehicle_year", models.PositiveIntegerField()),
                ("vehicle_fuel", models.CharField(max_length=50)),
                ("vehicle_mileage", models.PositiveIntegerField()),
                ("vehicle_transmission", models.CharField(max_length=50)),
                ("vehicle_engine", models.CharField(max_length=50)),
                ("vehicle_seats", models.PositiveIntegerField()),
                ("vehicle_doors", models.PositiveIntegerField()),
                ("vehicle_description", models.TextField()),
                ("vehicle_type", models.CharField(max_length=50)),
                (
                    "vehicle_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehicle_images/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Rented", "Rented"),
                            ("Under Maintenance", "Under Maintenance"),
                            ("Inactive", "Inactive"),
                            ("Reserved", "Reserved"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("vehicle_airbags", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "vehicle_brake_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "vehicle_start_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "vehicle_weight",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tempo_seats", models.PositiveIntegerField(blank=True, null=True)),
                ("tempo_doors", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "vehicle_capacity",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.admin_register",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.driver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, unique=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.country",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="driver",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="admin_panel.state"
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="admin_panel.state"
            ),
        ),
        migrations.AddField(
            model_name="admin_register",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="admin_panel.state"
            ),
        ),
    ]
