# Generated by Django 5.2.3 on 2025-06-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company_vehicle",
            name="tempo_doors",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="company_vehicle",
            name="tempo_seats",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="company_vehicle",
            name="vehicle_airbags",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="company_vehicle",
            name="vehicle_doors",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="company_vehicle",
            name="vehicle_mileage",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="company_vehicle",
            name="vehicle_seats",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="company_vehicle",
            name="vehicle_year",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
