# Generated by Django 5.2.3 on 2025-07-04 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_alter_company_vehicle_tempo_doors_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driver",
            old_name="profile_image",
            new_name="driver_profile_image",
        ),
    ]
