# Generated by Django 5.2.3 on 2025-07-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_rename_profile_image_driver_driver_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_vehicle',
            name='vehicle_engine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available'), ('Leave', 'Leave')], default='Available', max_length=20),
        ),
    ]
