# Generated by Django 5.2.3 on 2025-07-05 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0004_alter_company_vehicle_vehicle_engine_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="locations",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "location_pincode",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "location_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "location_landmark",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "location_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional: Paste a Google Maps link or custom URL",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "location_image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="location_images/"
                    ),
                ),
                (
                    "location_image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="location_images/"
                    ),
                ),
                (
                    "location_image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="location_images/"
                    ),
                ),
                (
                    "location_image4",
                    models.ImageField(
                        blank=True, null=True, upload_to="location_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.admin_register",
                    ),
                ),
                (
                    "location_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.city",
                    ),
                ),
                (
                    "location_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.country",
                    ),
                ),
                (
                    "location_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.state",
                    ),
                ),
            ],
        ),
    ]
